### ISSUE TITLE
Cargar por url falla

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#100]
Al cargar la siguiente url en otra ventana da un error 500.

https://gist.githubusercontent.com/sigdeletras/83bbb48c5856660a4b72/raw/82bb78fd3eb4a3cfece874d9e528cb7b2bcfc105/map.geojson

**Comment by jmmluna** [comment]
Es curioso este error, la URL se carga correctamente desde la plataforma. Cuando se genera la URL a compartir y se carga desde la URL de GeoWE es cuando no inserta elementos en la capa y da el error en la consola de "mal formado". Lo he probado con otras URLs y funcionan bien. Es un caso puntual que habrá que estudiar detenidamente. Parece que puede ser que haya algo que no le guste de la URL del fichero en el queryparam de la petición.

**Comment by jmmluna** [comment]
Resuelto en la versión 1.0.3-Beta, error detectado en el nombre del parámetro correspondiente al formato de la capa
