### ISSUE TITLE
Herramienta espacial Buffer

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#102]
Generar el buffer en una nueva capa, igual que las herramientas de envelope y centroide.

**Comment by i62lotor** [comment]
Ahora la herramienta buffer opera de manera simiar las de centroide y envelope. Se crea el buffer en de los elementos seleccionados una capa nueva. Si no hay ningún elemento seleccionado se crea para todos los elementos de la capa.

Disponible en la versión 0.2.13
