### ISSUE TITLE
Cambiar orden en la definición de atributos de una capa

### ISSUE THREAD

**Issue by jmmluna** [geowe/geowe-core#107]
Al añadir atributos, podría ser interesante que apareciese una opción de subir o bajar el atributo.

**Comment by fmarellano** [comment]
[GeoWE_Editando Atributos.pdf](https://github.com/geowe/geowe-core/files/259074/GeoWE_Editando.Atributos.pdf)

**Comment by fmarellano** [comment]
Adjunto documento con pantallazo del caso.

**Comment by i62lotor** [comment]
A partir de la versión 0.2.36, estará disponible. Para subir/bajar la fila se hace arrastrandola hasta la posición deseada.
