### ISSUE TITLE
Al cargar los tiles de basados en OpenStreetMap no sale la atribución definida en la licencia

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#108]
Para más info [http://www.openstreetmap.org/copyright](http://www.openstreetmap.org/copyright)

**Comment by i62lotor** [comment]
En la siguiente versión demo, aparecerá la atribución de los servicios de OSM, en la parte inferior izquierda (al lado de la barra de escala).

Muchas gracias por la apreciación.

**Comment by sigdeletras** [comment]
Pues perfecto y buen trabajo
