### ISSUE TITLE
Revisar las condiciones de uso de los servicios WMS para añadir la atribución

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#109]

**Comment by i62lotor** [comment]
En la siguiente versión demo, aparecerá la atribución, de los servicios que lo requieran, en la parte inferior izquierda (al lado de la barra de escala).

Si a partir de la siguiente versión (fecha estimada de despliegue 20-05-2016) alguna de las capas del catálogo, que obliguen a mostrar la atribución, no lo reflejara, por favor haznoslo saber.

Muchas gracias por la apreciación.

**Comment by sigdeletras** [comment]
Estaré atento
