### ISSUE TITLE
The cadastral WMS service doesn't load

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#110]

**Comment by jmmluna** [comment]
La WMS de Catastro desde el Catálogo de capas, en principio la carga bien:
![geowe-catastro](https://cloud.githubusercontent.com/assets/17873390/15176399/3661d096-176b-11e6-9186-75a7ec1de721.png)

¿Cómo has intentado cargarla?

**Comment by sigdeletras** [comment]
Lo cargo desde el Catálogo y me sigue sin cargar. La cosa es que recuerdo haberlo cargado antes. Y no es por el zum. Y la cosa es que añade el servicio porque los metadatos se cargan (Descripción)

**Comment by sigdeletras** [comment]
Lo he cargado desde Añadir capa WMS y me carga perfectamente

**Comment by jmmluna** [comment]
En principio debería funcionar desde el Catálogo y desde "Cargar WMS", la carga del Catálogo realmente es la misma petición que desde el WMS.
