### ISSUE TITLE
Al cargar WMS con transparencia no se ve bien el logo

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#111]
![geowe](https://cloud.githubusercontent.com/assets/4746157/15173763/51d3a046-175e-11e6-95d3-66ae16eeb384.png)

**Comment by jmmluna** [comment]
Qué raro, yo lo he estado probando y se ve bien:
![geowe-transpariencia-wms](https://cloud.githubusercontent.com/assets/17873390/15176756/ef62d09e-176c-11e6-853f-fa54a862be68.png)

**Comment by jmmluna** [comment]
He observado que es en función del Zoom de la zona y de los elementos que contenga la capa WMS. Se queda detectado y se resolverá lo antes posible. 
Muchas gracias

**Comment by i62lotor** [comment]
resuelto en la versión 0.2.12. Estará disponible en el siguiente despliegue de la demo.

Gracias por el aporte.
