### ISSUE TITLE
Error en mensaje de Confirmación al eliminar una capa 

### ISSUE THREAD

**Issue by fmarellano** [geowe/geowe-core#112]
Buenos días.

Al tratar de eliminar una capa que tenemos cargada, nos sale un mensaje de confirmación. En el mismos se ha colado una “d” en lugar de una “r” en el mensaje, diciendo “Está segudo de eliminar 1 capa?”. 

Quizá también sería interesante que apareciese una interrogación al inicio de la pregunta.

Muchas gracias.

[20160512_Error GeoWE.pdf](https://github.com/geowe/geowe-core/files/260748/20160512_Error.GeoWE.pdf)

**Comment by geowe** [comment]
Muchas gracias por la apreciación, quedará corregido en la próxima versión.
