### ISSUE TITLE
Visualizar WKT de un elemento y poder aplicar cambios via WKT

### ISSUE THREAD

**Issue by jmmluna** [geowe/geowe-core#113]
Obtener el WKT de un elemento en concreto.  Seria interesante desde el punto de vista de la edición cuando algún elemento se carga con errores topologico poder ver su WKT, poder cambiarlo y aplicarlo.

**Comment by i62lotor** [comment]
En la versión 0.2.20 se implementa la visualización del WKT de un elemento, desde el diálogo de información/edición

**Comment by i62lotor** [comment]
En la versión 0.2.23 se puede cambiar el WKT. Esto hará que el elemento modificado se elimine y se cree uno nuevo (clon) con los mismos atriburos y valores alfanuméricos y con la nueva geometría.

**Comment by i62lotor** [comment]
Disponible en la versión 0.2.24
