### ISSUE TITLE
Elegir atributos a mostrar en la vista rápida

### ISSUE THREAD

**Issue by i62lotor** [geowe/geowe-core#114]
Al mostrar la vista rápida (tooltip) de la información de un elemento del mapa, se muestran los primeros atributos definidos. Sería interesante poder seleccionar los atributos que quieres que se muestren.

**Comment by atamunoz** [comment]
Se ha incluido en el diálogo de atributos de la capa una nueva check que define si el atributo se muestra en la vista rápida (tooltip), de manera que el usuario pueda decidir qué atributos se van a mostrar.
