### ISSUE TITLE
Necesida de un target ='_blank' en enlaces de WMS info

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#116]
Al consultar atributos de un WMS, en este caso de Catastro, que contienen un enlace sería necesario que se abrieran en una nueva ventana ya que se carga sobre la misma de Geowe y provoca el borrado de los datos de la sesión.
Habría que mirar si pasa los mismo cuando tenemos atributos tipo enlace vinculados a las capas vectoriales que se creen o carguen.

**Comment by sigdeletras** [comment]
Lo he comprobado en atributos de tipo enlace para capa vectorial y no ocurre.

**Comment by i62lotor** [comment]
Lo mostrado en el diálogo del WMS info  es lo que devuelve el servidor WMS. Habría que abrirlo pulsando CRTL.
Al intentar abrir un enlace en la ventana donde está GeoWE, se advierte de que se va a abandonar la aplicación.

Para la próxima versión estudiaremos, si es posible,  una solución mas adecuada, por el momento se va a mostrar un mensaje de advertencia en el diálogo de información de WMS.

**Comment by i62lotor** [comment]
Solucionado a partir de la versión 0.2.37.
Los enlaces se abrirán en una nueva pestaña.
