### ISSUE TITLE
Definir un tamaño máximo al popup de la vista rápida

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#117]
En caso de tener campos muy largos ocupa la extensión  de la vista o más. Comprobarlo en la capa de rutas.

**Comment by i62lotor** [comment]
Se limita en nº de carácteres a 30, para que el tooltip no sea demasiado grande. Esto puede ocasionar que no se puede ver el valor completo del atributo, pero se puede ver desde el diálogo de información/Edición.
