### ISSUE TITLE
Eliminar varios elementos a la vez

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#12]
Una mejora para la herramienta de eliminar elemento del mapa sería que pudiese eliminar varios elementos a la vez. Por ejemplo los seleccionados.

**Comment by i62lotor** [comment]
implementado en la versión 0.1.63-Alpha.
Se pueden eliminar desde el diálogo LayerInfoDialog.
Se eliminarán todos los elementos seleccionados.

**Comment by i62lotor** [comment]
en la versión 0.1.70-Alpha se pueden borrar varios elementos a la vez desde la herramienta de borrado, del panel principal de herramientas. Se borran los elementos seleccionados.
