### ISSUE TITLE
New what3words API

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#123]
Full details of API v2 can be found on our [developer site](http://what3words.us7.list-manage1.com/track/click?u=a267440431b40ff06ac629049&id=be8ef0678f&e=d81a55e0c8) including a handy [migration guide](http://what3words.us7.list-manage.com/track/click?u=a267440431b40ff06ac629049&id=309bf3899f&e=d81a55e0c8) for moving your API v1 application to v2.

**Comment by atamunoz** [comment]
Modificadas las llamadas directa e inversa de la funcinalidad de W3W para ajustarlas a la versión v2 de la API de What3Words.
