### ISSUE TITLE
Los círculos dibujados siempre tiene errores geométicos.

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#130]
Al aplicar la validación a un círculo dibujado siempre presenta el siguiente error:
Error en orientación del polígono

**Comment by i62lotor** [comment]
La herramienta de dibujar círculo lo dibuja como un "polígono regular", y siempre los los vértices en sentrido contrario a las agujas del reloj (counterclockwise). Para solucionarlo y que no de error en la validación se realiza un buffer de 0 a la geometría, quedando los vértices en sentido de las agujas del reloj (clockwise), como manda el estándar SFS.
