### ISSUE TITLE
Iconos de Contacto con color de poco contraste

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#131]
Al cargar capas base con fondos claros (OSM, Catastro...) los iconos de contacto, menos el de Información,  no se aprecian bien. 

A "Información" le falta  "title"

![seleccion_109](https://cloud.githubusercontent.com/assets/4746157/16109753/b965dad6-33aa-11e6-887f-5ed934fac0c0.png)

**Comment by i62lotor** [comment]
Ya lo vimos en su día. El tema está en que si se ponen oscuros, no se ven bien con otras capas. Pensamos también en poner cada uno de su color, es decir, el de google+ rojo, el de facebook azul,...

¿Se te ocurre alguna otra opción?

**Comment by sigdeletras** [comment]
Yo lo pondría como el de info que se ve bien en los dos tipos de fondo. Ya lo tenéis resuelto!!!

**Comment by geowe** [comment]
Pero se quisiera diferenciar lo que es un enlace a un sitio externo, de un boton de funcionalidad interna. Al menos para esta version. 
Para versiones personalizadas se podria poner enlaces u otras herramientas.

**Comment by sigdeletras** [comment]
Vale. No entendía la diferencia

**Comment by i62lotor** [comment]
En la próxima versión se mostrarán cambios, a ver que tal.
