### ISSUE TITLE
Diálogo de análisis espacial

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#132]
El parámetro distancia, no tiene sentido si no es una tolerancia en todas las operaciones que no sean buffer.

Cuando calculas un buffer el cuadro de dialogo mantiene el valor de la distancia, cuando debería ser 0 o nulo para otras operaciones.
[Por Alejandro Alameda]

**Comment by jmmluna** [comment]
Resuelto en la versión 0.2.46
