### ISSUE TITLE
Validaciones en geometrías grandes

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#133]
Si bien la herramienta de validación te indica Qué geometría tienen error, no te indica Dónde.

En geometrías grandes o complicadas como ríos / caminos, esto puede ser un problema.
[Por Alejandro Alameda]

**Comment by i62lotor** [comment]
Implementado en la versión 1.4.8.
Ahora la capa de resultado de la validación tendrá un color de relleno y de línea Rojo. Donde además de la geometría no válida se marcarán las coordenadas (puntos) que pueden provocar el problema
