### ISSUE TITLE
Diálogo de análisis espacial

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#135]
Al pulsar en Aceptar sin capas seleccionadas se cierra el diálogo

**Comment by i62lotor** [comment]
Propondría rediseñar el diálogo.
1. Poner una breve descripción del significado de análisis espacial
2. Combo para seleccionar la operación
3. Al seleccionar la operación se visualizará/habilitará los datos requeridos para cada operación. Por ejemplo para el buffer se requiere una capa y la distancia, pero para la intersección se requieren 2 capas.
4. Bottón de ayuda (quizá en la cabecera del diálogo) donde se explique que hace cada operación). Podría ser un enlace externo.

![ejemplo_dialogo_analisis](https://cloud.githubusercontent.com/assets/17040784/16227575/bc5e560e-37b1-11e6-9b7b-7f759bd34eb0.png)

**Comment by jmmluna** [comment]
En la versión 0.2.46 se resuelve quedando rediseñado la herramienta de análisis espacial y realizando un mayor control de los parámetros de entrada a la hora de realizar la operación seleccionada
