### ISSUE TITLE
Carga de servicios de tiles TS/TMS

### ISSUE THREAD

**Issue by ghost** [geowe/geowe-core#151]
Sugerencia: Si el catálogo permite añadir fondos ráster provenientes de servicios de tiles TS/TMS, creo que sería muy interesante que también se pudieran añadir a partir de url's especificadas por los usuarios.

**Comment by i62lotor** [comment]
Gracias por la sugerencia Gonzalo. Ahora mismo solo está soportado la carga de WMS. 
Desde la herramienta de añadir capa ráster, en el administrador de capas.
![geowe - 1 0 5-add-wms](https://cloud.githubusercontent.com/assets/17040784/17846372/5aa1f156-6848-11e6-974a-55946bda4900.png)

Vamos a ver la posibilidad de incorporar la carga desde los servicios que propones (TS/TMS).

Muchas gracias.
Un saludo

**Comment by jmmluna** [comment]
Primeras pruebas de integración de servicios WMTS en GeoWE. Se ha testeado con servicios WMTS de ortofotos del PNOA del IGN
Servicio Web de Mapas Teselado conforme al perfil INSPIRE de Web Map Tile Service (WMTS) 1.0.0
Si todas las pruebas van bien para el viernes se podrá disponer de esta nueva funcionalidad.
![geowe-wmts-pnoa](https://cloud.githubusercontent.com/assets/17873390/17891083/0786ae1a-693a-11e6-9973-23ff014bf09d.JPG)

**Comment by jmmluna** [comment]
Gonzalo ¿podrías facilitarnos datos de servicios TMS para hacer pruebas?

**Comment by ghost** [comment]
Hola, me encuentro fuera de casa así que hoy no puedo daros mucha información (el lunes lo amplío).
Estas son las urls, de los servicios TS/TMS que tenemos operativos en IDErioja:
Mapa Base IDErioja: http://ts0.larioja.org/mb.php?z={z}&x={x}&y={y}Ortofoto máxima actualidad: http://ts0.larioja.org/mb_raster.php?z={z}&x={x}&y={y}Relieve de La Rioja: http://ts0.larioja.org/mb_relieve.php?z={z}&x={x}&y={y}Especificación TMS:
Mapa Base IDErioja: http://tms0.larioja.org/mb.php?z={z}&x={x}&y={y}Ortofoto máxima actualidad: http://tms0.larioja.org/mb_raster.php?z={z}&x={x}&y={y}Relieve de La Rioja: http://tms0.larioja.org/mb_relieve.php?z={z}&x={x}&y={y}
Responden tanto a protocolos http como https (este es otro aspecto que habría que tener en cuenta)
En el caso de OSM el servicio OSM Base Maps es:
http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.pngEjemplo de logroño en un nivel 12: http://a.tile.openstreetmap.org/12/2020/1513.png

En los servicios que incluyen un parámetro {s} para servir los tiles por varios hilos, este puede venir sustituido por los valores 1,,,3,4, ó a,b,c,d, 
Hay una url muy interesante de Google. que visualiza muy bien las diferencias de direccionamiento de las coordenadas x,y entre un servicio TS(Google) o TMS(OSGEO):

http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/

Lo dicho, este lunes miro mis listados de urls y amplío este correo.
Que tengáis un buen fin de semana.
GonZaLo

**Comment by gonzalolopezgarcia** [comment]
Hola, en este directorio de github existe una gran colección de tileservers: nextgis/quickmapservices_contrib  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
nextgis/quickmapservices_contrib
 
quickmapservices_contrib - Contributed data sources for QuickMapServices
  |   |

  |

  |

  En los ficheros metadata.ini se encuentran las urls y los detalles específicos de cada conexión.
Un saludo.
GonZaLo

Enviado desde Yahoo Mail con Android 
 
  El dom. 28 28e ago. 28e 2016 a las 9:30, Gonzalo López García<gonzalolopezgarcia@yahoo.es> escribió:   Hola, me encuentro fuera de casa así que hoy no puedo daros mucha información (el lunes lo amplío).
Estas son las urls, de los servicios TS/TMS que tenemos operativos en IDErioja:
Mapa Base IDErioja: http://ts0.larioja.org/mb.php?z={z}&x={x}&y={y}Ortofoto máxima actualidad: http://ts0.larioja.org/mb_raster.php?z={z}&x={x}&y={y}Relieve de La Rioja: http://ts0.larioja.org/mb_relieve.php?z={z}&x={x}&y={y}Especificación TMS:
Mapa Base IDErioja: http://tms0.larioja.org/mb.php?z={z}&x={x}&y={y}Ortofoto máxima actualidad: http://tms0.larioja.org/mb_raster.php?z={z}&x={x}&y={y}Relieve de La Rioja: http://tms0.larioja.org/mb_relieve.php?z={z}&x={x}&y={y}
Responden tanto a protocolos http como https (este es otro aspecto que habría que tener en cuenta)
En el caso de OSM el servicio OSM Base Maps es:
http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.pngEjemplo de logroño en un nivel 12: http://a.tile.openstreetmap.org/12/2020/1513.png
|   |
|   |  |   |   |   |   |   |
|  |
|  |
| Ver en a.tile.openstreetmap.org | Vista previa por Yahoo |
|  |
|   |



En los servicios que incluyen un parámetro {s} para servir los tiles por varios hilos, este puede venir sustituido por los valores 1,,,3,4, ó a,b,c,d, 
Hay una url muy interesante de Google. que visualiza muy bien las diferencias de direccionamiento de las coordenadas x,y entre un servicio TS(Google) o TMS(OGC): 
Tiles à la Google Maps: Coordinates, Tile Bounds and Projection - conversion to EPSG:900913 (EPSG:3785) and EPSG:4326 (WGS84)
|   |
|   |  |   |   |   |   |   |
| Tiles à la Google Maps: Coordinates, Tile Bounds and Pro...Addressing tiles: same tile bounds with different indexes  |
|  |
| Ver en www.maptiler.org | Vista previa por Yahoo |
|  |
|   |


Lo dicho, este lunes miro mis listados de urls y amplío este correo.
Que tengáis un buen fin de semana.
GonZaLo
      De: José María Martínez Luna <notifications@github.com>
 Para: geowe/geowe-core <geowe-core@noreply.github.com> 
CC: gonzalolopezgarcia <gonzalolopezgarcia@yahoo.es>; Author <author@noreply.github.com>
 Enviado: Viernes 26 de agosto de 2016 14:26
 Asunto: Re: [geowe/geowe-core] Carga de servicios de tiles TS/TMS (#151)
  
Gonzalo ¿podrías facilitarnos datos de servicios TMS para hacer pruebas? —

**Comment by ghost** [comment]
Parece que yahoo mail no se lleva muy bien con los issues de Github, así que reescribo el mensaje desde aquí:

En la url de github https://github.com/nextgis/quickmapservices_contrib/tree/master/data_sources
podéis encontrar una amplia colección de tile servers.

El fichero metadata.ini de cada directorio contiene la url y los detalles necesarios de cada servicio.

Aunque no los he rastreado todos, y aunque el parámetro Type = TMS creo que la práctica mayoría direcciona los tiles como lo hace Google (TS) y no TMS (http://wiki.osgeo.org/wiki/Tile_Map_Service_Specification) (1)

Un saludo

GonZaLo

**Comment by jmmluna** [comment]
Muchas gracias por facilitar la información.
Seguimos en contacto.
Un saludo.

**Comment by jmmluna** [comment]
TMS integrado y funcionando en la version de GeoWE 1.1.0 - Beta
![geowe - 1 1 0-beta tsm](https://cloud.githubusercontent.com/assets/17873390/18070083/d14f93fe-6e4b-11e6-87c9-066b48ddf02c.png)

**Comment by jmmluna** [comment]
Más pruebas TMS con GeoWE
![geowe-tms-2](https://cloud.githubusercontent.com/assets/17873390/18083350/105ed7d8-6ea3-11e6-9b78-cf87319772f6.JPG)

![geowe-tms-1](https://cloud.githubusercontent.com/assets/17873390/18083324/f9fb7ae6-6ea2-11e6-9af5-7d88f50dc8ae.JPG)

Para la versión 1.1.0-Beta se encontrará operativo.
Gracias Gonzalo por los casos de prueba, han sido de gran utilidad para testear bien la herramienta
Saludos!!!
