### ISSUE TITLE
Posible desajuste de coordenadas Google Satellite y TMS

### ISSUE THREAD

**Issue by ghost** [geowe/geowe-core#163]
Probando la nueva funcionalidad de fondos ráster TS/TMS, creo que puede haber algún tipo de desajuste entre los sistemas de coordenadas utilizados por la imagen de Google Satellite y los ráster TMS's
![desajuste](https://cloud.githubusercontent.com/assets/5079197/18251600/320ecb2c-738a-11e6-9c03-7d814a20a53a.jpg)

**Comment by jmmluna** [comment]
Gracias Gonzalo,  lo he comprobado y efectivamente existe un desplazamiento provocado por la definición de los parámetros del mapa: resolución y extensión máxima.

Estará resuelto para la siguiente versión !!!
Saludos!!

**Comment by ghost** [comment]
Fenómenal!

Un saludo para todo el equipo de desarrolladores y enhorabuena.

**Comment by jmmluna** [comment]
Hola Gonzalo, ya se ha cerrado la versión 1.1.1-Beta. Te adjunto una captura con la que se ha comprobado que no exista desplazamiento en las capas TMS. Si ves cualquier otra cosa no dudes en contactar con nosotros.  Aprovecho para comentarte que se irá complementando el sopote de carga de servicios de Tiles.
Seguimos en contacto.
Saludos!!
![geowe 1 1 1 beta](https://cloud.githubusercontent.com/assets/17873390/18384336/41dd50d4-768a-11e6-9b4f-55424c6dd2dc.png)
