### ISSUE TITLE
Informes de datos alfanumérico

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#17]
Sería interesante poder sacar informes, al menos en html, de la información alfanumérica de una capa, un elemento o varios.

**Comment by geowe** [comment]
Se puede exportar a csv desde el dialogo de info/edicion de elemento

**Comment by i62lotor** [comment]
Se puede exportar a csv desde el diálogo de búsqueda de elementos. Exporta la lista de elementos seleccionados

**Comment by geowe** [comment]
Se puede exportar a csv todos los elementos de la capa. A partir de la versión 0.1.36

**Comment by geowe** [comment]
En el diálogo de información de la capa se puede visualizar un resumen de la información de la capa, y descargarlo como html

**Comment by i62lotor** [comment]
A partir de la versión 1.1.0 se muestra una tabla con el listado de todos los elementos y el valor de sus atributos

**Comment by i62lotor** [comment]
Los elementos se muestran tabulados.
