### ISSUE TITLE
mejorar diálogo de información de capa

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#170]
Sería importante mejorar la visualización del listado de elementos en el diálogo de información de capa.

**Comment by i62lotor** [comment]
Rediseño de los elementos en el diálogo. 
Lo tengo pendiente de subir a git.

**Comment by i62lotor** [comment]
Disponible a partir de la versión 1.1.2-Beta

**Comment by atamunoz** [comment]
Cambio de la vista de datos que estaba como ListView a formato Grid (tabla).
Disponible en la versión 1.2.0-Beta.
