### ISSUE TITLE
Enlaces en el valor de atributo

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#18]
Sería interesante permitir enlaces (link) como valor de un atributo. De esta manera al visualizar la información de un elemento podríamos navegar a una web con más información al respecto.

**Comment by i62lotor** [comment]
Se pueden meter enalces como valor de atributo, para ello solo hay que empezar la cadena con http

**Comment by geowe** [comment]
Se pueden añadir imágenes (enlazadas por url). Se mostrará una miniatura en el valor del atributo. Para ello hay que rellenar el valor empezando con img:
por ejemplo:
img:http://url-imagen
