### ISSUE TITLE
Formulario de logueo en Github para importar capas de repositorio

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#186]
¿Podrían usarse los mismso pasos que hay que dar para exportar una capa a un repositorio de Github para importar capas desde la cuenta de Github?
La opción de cargar por URL la dirección del raw desde Github es bastante poco intuitiva.

**Comment by jmmluna** [comment]
Resuelto en la versión 1.3.8
Se añade la pestaña GitHub en la importación de capas. Introduciendo el nombre de usuario de GitHub se podrá navegar (repositorios y rutas de carpetas) hasta localizar el fichero que se desea cargar. En este sentido, se ha habilitado la carga múltiple de ficheros, teniendo en cuenta que deben tener el mismo sistema de referencia que se seleccione y el mismo formato.
También se ha añadido la utilidad de GitHub en la pestaña de importar por URL, de tal manera que se facilite la búsqueda de un fichero en GitHub para obtener su URL y agilizar en la generación de URL compartida.

**Comment by sigdeletras** [comment]
Magnífico trabajo y de gran utilidad.
