### ISSUE TITLE
Creación/Carga de archivo de proyecto GeoWE

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#187]
ya que quedan solucionados la creación, edición, carga y guardado de datos vectoriales estaría bien poder salvar el archivo de configuración de un proyecto en GeoWE. Estoy pensando en algún fichero  de marcas, que se pudiera cargar en cualquier momento y poder retomar el trabajo que se ha realizado en otras sesiones.

**Comment by jmmluna** [comment]
En la versión 1.4.0 de GeoWE estarán disponibles dos nuevas herramientas que van a permitir a GeoWE cargar y guardar una sesión de trabajo en formato gpr (GeoWE Project). Para esta versión de formato de proyecto GeoWE (1.0.0) se exportarán todas las capas vectoriales activas durante la sesión actual de trabajo.
