### ISSUE TITLE
Longitud de líneas durante la edición

### ISSUE THREAD

**Issue by jmmluna** [geowe/geowe-core#190]
Permitir al usuario conocer la lonfigud/medida de la línea en el proceso de dibujo para elementos de tipo polígono y línea

**Comment by i62lotor** [comment]
Implementado, en la versión 1.4.7, para dibujar líneas.

**Comment by i62lotor** [comment]
Implementado también para polígonos en el fork i62lotor/geowe-core.
Cuando se haga pull-request se puede cerrar este issue

**Comment by i62lotor** [comment]
mergeado.
