### ISSUE TITLE
Nombre de la capa en "Añadir capa raster"

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#215]
En el fomulario de "Añadir capa raster" exixte un campo denominado "Nombre de la capa" para todas las pestañas. En el caso de servicios WMS y WMST hace refencia a la capa a cargar del servicio, mientras que para el TMS es el nombre que se dará a la capa una vez cargada. 

En el caso de servicios OGC podría cambiarse a "Nombre de la capa WMS a carga"

**Comment by i62lotor** [comment]
corregido en la versión 1.3.4
