### ISSUE TITLE
WFS: campo de filtro marcado como vacio

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#219]
El campo de filtro cql se queda marcado como vacio aunque este deshabilitado.

**Comment by i62lotor** [comment]
Solucionado en la versión 1.3.5.
Se permite que el campo quede vacía. Eso indicará que no se ha de aplicar ningún filtro, y se obtendrán todos los elementos, hasta alcanzar el máximo número indicado en el campo Max. Elementos, que si tuviese un valor de 0 devolvería todos los elementos.
