### ISSUE TITLE
GeojsonCSS

### ISSUE THREAD

**Issue by ghost** [geowe/geowe-core#220]
Hola de nuevo!, ¿sabéis que existe un [plugin para Leaflet](https://github.com/albburtsev/Leaflet.geojsonCSS) que permite representar el [formato Geojson CSS](http://wiki.openstreetmap.org/wiki/Geojson_CSS), pero que no existen muchas aplicaciones capaces de producirlo?

Entiendo que dentro de Geowe sería razonablemente sencillo añadir una opción para guardar la información en formato Geojson CSS que permitiera almacenar al mismo tiempo los datos y los principales parámetros de simbolización establecidos por el usuario.

Esto ofrecería la posibilidad de recuperar posteriormente los datos y su simbología en una sola operación así como la oportunidad de representar la información en Leaflet y en otras aplicaciones, tal como el productor la ha diseñado.

Un saludo a todos.

GonZaLo

**Comment by jmmluna** [comment]
Hola Gonzalo,

ya disponemos de una primera versión de prueba de guardar información geográfica en formato GeoJSON CSS. En esta versión se va a exportar/importar el formato aplicando estilos básicos a nivel de capa. ¿Tenéis datos en este formato para realizar pruebas?. También estoy validando el formato a través de Leaflet. Cuanta más información mejor!!!, así nos aseguramos la compatibilidad del formato.

Un saludo!!

**Comment by jmmluna** [comment]
Buenas @gonzalolopezgarcia,

aquí te muestro un adelanto de la integración del formato GeoJSON CSS (implementación Leaflet) en GeoWE con estilos a nivel de capa. 
![geojson-testing](https://cloud.githubusercontent.com/assets/17873390/22463263/2007c88e-e7b1-11e6-9950-9a8c9a4c2be0.png)

**Comment by jmmluna** [comment]
Formato GeoJSON CSS con estilos a nivel de capa disponible en la versión 1.4.1

**Comment by ghost** [comment]
Antes de nada daros la enhorabuena y las gracias por tener este Issue en consideración. Como siempre, no se os resiste nada.

Si necesitáis algún GeoJSON de ejemplo, los mapas interactivos de IDErioja tienen una opción para descargar los datos que utiliza este formato.

Este es el enlace general: https://www.iderioja.larioja.org/index.php?id=30&lang=es
 y este enlace uno de ellos: https://www.iderioja.larioja.org/vct/index.php?c=4c4c307462644f70447978627364703072424c524c413d3d&s=1&cm=0

**Comment by ghost** [comment]
También podéis probar los GeoJSON renderizándolos en Leaflet con la API de IDERioja. Os paso la documentación de la opción. es muy sencilla de implementar:
https://github.com/iderioja/doc_api_iderioja/blob/master/docs/opciones/capa_geojson.md
