### ISSUE TITLE
Edición de datos desde "Información de la capa"

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#224]
Para edición alfanumérica masiva de datos sería interesante habilitar la actualización o completado de datos en la tabla que se presenta en el diálogo  "Información de la capa"

**Comment by i62lotor** [comment]
Eso habilitaría la edición en la misma tabla, pero uno por uno, no masivamente.

**Comment by atamunoz** [comment]
Implementado en la versión 1.4.16. Se ha incluido una nueva opción en el diálogo de información de capa que permite mostrar un grid de mayor tamaño sobre el que se pueden editar directamente los datos alfanuméricos de las features de la capa. NOTA: Los cambios no se aplican hasta pulsar el botón OK en el diálogo de edición.

Como futuras mejoras se plantea incluir la edición directamente desde el propio diálogo de información de capa, con objeto de aprovechar la paginación y las herramientas de este diálogo.
