### ISSUE TITLE
Zum a elementos puntuales desde "Información de la capa"

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#225]
Para elementos puntuales, el zum al punto que se hace desde "Información de la capa" es demasiado grande (según la escala numñerica 1:3). Esto produce tras realizar dicho zum desaparescan la mayoría de capas base ya que no están "tileadas" para esa escala. Por ejemplo la Google se representa, según los niveles de zum definidos en GeoWE ,  a partir de la escala 1:334 y OSM aparece a Escala 1:1334

**Comment by i62lotor** [comment]
Hola Patricio.
He pensado la siguiente solución:
Si el elemento es un punto al hacer el zoom al elemento este se centrará y el nivel de zoom se establecerá a 18 (la mayoría de las capas ráster tienen imágenes a ese nivel de zoom).

Estará disponible en la siguiente versión.
Si se te ocurre algo mejor dímelo.
Gracias y un saludo.
Esta implementado en mi fork (i62lotor/geowe-core)

**Comment by i62lotor** [comment]
Incluido en el repo oficial en la versión 1.3.7

**Comment by sigdeletras** [comment]
Lo veo perfecto \°/
