### ISSUE TITLE
Separador de campo archivo CSV exportado

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#227]
Al exportar una capa de tipo poligonal o lineal en formato CSV, el carácter delimitador es la coma. Debido a esto si se quiere cargar esta información como archivo delimitado en un SIG de escritorio, por ejemplo QGIS, el uso de la coma como delimitador hace que para cada coordenda de un nodo se generere una columna.

![sincomillas](https://cloud.githubusercontent.com/assets/4746157/20029750/8915952c-a355-11e6-913d-4f51f641816b.png)

Esto se podría solucionar de dos formas:

- No usando la coma como delimitador, usándose por ejemplo el punto y como

- "Encerrando" los valores de lo registros en tre comillas simples o dobles
![condelimitador](https://cloud.githubusercontent.com/assets/4746157/20029753/954fbb74-a355-11e6-96b2-83f51784ec7e.png)

**Comment by i62lotor** [comment]
A partir de la versión 1.3.6 el delimitador del csv es **;** (punto y coma)
