### ISSUE TITLE
Importación de archivo CSV

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#228]
Al igual que se puede exportar la capa en formato CSV con la geometría en WKT, se debería poder importar un archivo con esta misma estructura. He porbado a cargar un CSV obtenido con GeoWE desde local y no lo hace

Como herramienta de muchísima utilizada, se podría completar la importación de archivos CSV donde los datos de X/Y o longitud/latitud estuvieran en un par de columnas. Al seleccionar este tipo se debería indicar el nombre de las dos columnas que incluyen las coordenadas o en el caso que la geometría fuera WKT la columna con esa información.

Como os comento es una herramienta de mucha utilidad, uso y necesidad. Muchas usuarios que no manejan SIG neesitan ver representados geográficamente listados de coordendas obtenidos por ejemplo de Boletines oficiales. Una cargados estos datos, GeoWE sería una herramienta magnífica para completar datos alfanuméricos o completar los geográficos.

**Comment by i62lotor** [comment]
Hola Patricio.
la importación de CSV se queda registrado como mejora a abordar lo antes posible.
Respecto a  guardar la información geográfica de punto en dos columnas, te comento que la opción recomendada para guardar datos geográficos es la que actualmente usa GeoWE (guardando el WKT), ya que permite almacenar geometrías diferentes, y no solo puntos. Piensa por ejemplo capas con puntos, líneas y polígonos. Puedes leer sobre el tema aqui [geoCSV](https://giswiki.hsr.ch/GeoCSV). En GeoWE se adapta el formato para que en la primera fila incluya el nombre de los atributos.

La mejora que propones sería una herramientas para determinados casos puntuales, evaluaremos el coste e intentaremos incorporarla en cuanto sea posible.

No obstante geoCSV (o csv) es un formato que no recomendaría para trabajar con datos geográficos.
Un saludo

**Comment by sigdeletras** [comment]
Hola Rafa

Desde un punto de vista técnico/desarrollo comparto tu punto de vista pero poniéndome del lado del usuario (que es lo que soy) no. 
Lo único que entiendo es que, en este aspecto, se pone bastante complicado hacer procesos sencillos que suelen ser bastante habituales en cualquier SIG (me dan un listado de coordenadas y quiero verlas en un mapa). Incluso si quiere obviar el SIG (por ejemplo porqe no se usarlo) tendría que generar, si se hacerlo, ese archivo con la columna WKT en una hoja de cálculo o incluso a mano.

**Comment by i62lotor** [comment]
En la versión 1.3.7 se podrá importar archivos csv generados con GeoWE, o cualquier otro que cumpla con las siguientes especificaciones:
- La primera línea serán los nombres de los atributos
- La última columna es la geometría en formato WKT
- El nombre del atributo de la geometría será WKT
- El separador del csv será el ; (punto y coma)

Se crea el issue #238 para acometer la importación de ficheros csv para elementos tipo punto, con las coordenadas en dos columnas (X e Y).

Patricio espero tus rigurosas pruebas. A ver que pasa cuando se quiere importar capas con un elevado número de elementos (1000 o mas). Con la capa de Lebrija que he probado no va mal.

**Comment by sigdeletras** [comment]
Genial. Espero con ganas poder probarlo. Un pequeño paso para GeoWE pero un gran paso para un humilde usuario SIG ;-)

**Comment by sigdeletras** [comment]
Y tras las pruebas, me comprometo a una entrada
