### ISSUE TITLE
Problemas de instalacion 

### ISSUE THREAD

**Issue by satluisbaltazar** [geowe/geowe-core#230]
como estas estimado... el siguiente problema esta en poder levantar el servicio ya que lo que estoy haciendo es hacer desde el appserv el mismos me sale el siguiente problema que a continuación detallo  

1
Failed to load resource: the server responded with a status of 404 (Not Found)
util.js:210 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keysTA.j @ util.js:210
2
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keysTA.j @ util.js:210
js:34 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error_.kb @ js:34
3
Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error_.kb @ js:34
![error_geowe](https://cloud.githubusercontent.com/assets/8813238/20112638/8b2fa60c-a5c3-11e6-9061-5d7000057f37.JPG)

**Comment by i62lotor** [comment]
hola @satluisbaltazar  los mensajes de la consola son normales si no dispones de key para  google apis.
En el [Readme](https://github.com/geowe/geowe-core/blob/master/README.md) del repositorio se explica.
Si no vas a usar mapas de Google, no es necesario. Por defecto está configurado un mapa de OSM.

Por otro lado, en la imagen que adjuntas veo que el despligue que has realizado muestar una url un poco extraña:

> http://localhost:8089/geowe-core-master/geowe-core-master/src/main/webapp/App.html

lo normal es que se hubiese generado un fichero geowe.war y al desplegarlo la url sería algo así:

> http://localhost:8089/geowe/App.html

¿Cómo has realizado el despliegue?

**Comment by i62lotor** [comment]
Hola @satluisbaltazar ¿conseguiste desplegar la aplicación?
¿Tienes algún otro problema?

**Comment by i62lotor** [comment]
Podrás encontrar información detallada de como desplegar GeoWE en el siguiente [post de rltsistemas]
(http://rltsistemas.blogspot.com.es/2016/12/montando-mi-sig-web-con-geowe.html)

Cierro este issue. Si tienes algún problema puedes volver a contactar.

Un saludo
