### ISSUE TITLE
Zoom asociado a la rueda del ratón deja de actuar >20

### ISSUE THREAD

**Issue by ghost** [geowe/geowe-core#231]
Hola a todos.
Trabajando con el fondo de imagen inicial que presenta Geowe, he comprobado que el zoom asociado a la rueda del ratón deja de actuar por encima del zoom 20. Una vez llego al zoom 21 o superior, no puedo utilizar la rueda del ratón para alejarme, siendo necesario recurrir a otra fórmula para hacerlo, como la de activar el menú zoom.
No es importante, pero es incómodo.

Un saludo y enhorabuena por la aplicación.

GonZaLo

**Comment by ghost** [comment]
Hola de nuevo, he comprobado que si se añade otra capa ráster a la inicial de google, el zoom y el pan vuelve a responder.

GonZaLo

**Comment by geowe** [comment]
Hola Gonzalo.
Efectivamente este problema parece estar asociado a las capas de google. Cuando a un nivel de zoom google pasa las imagenes a "vista 3d" o "inclinada".
En versiones de geowe donde no se carga la capa de google de partida no hemos visto que se produzca este problema.
Ahora mismo no sabemos porque pasa, pero esperamos tener una explicacion pronto y poder solventarlo.
La api de google maps tiene una opcion para evitar ese tipo de imagenes, pero las pruebas que hemos realizado no han sido satisfactorias.

Muchas gracias por tus aportaciones.
Un saludo.

**Comment by i62lotor** [comment]
Bueno, pues no solo pasa con las capas de Google. También pasa con algunas de OSM. 
Al parecer sucede cuando llega al zoom máximo al que se sirve las imágnes. Por ejemplo la capa de google al zoom 21 ya no sirve imágenes y se bloquea el zoom (desde la rueda del ratón), para OSM Mapnik pasa igual pero al zoom 19 (el máximo).

**Comment by i62lotor** [comment]
Para intentar paliar este problema se ha implementado un atajo de teclado para el zoom adentro y afuera.
Zoom In = tecla i
Zoom Out = tecla o
De esta manera si se bloquea la rueda del ratón se podrá controlar el zoom con estas teclas, en vez de tener que desplegar el menú para acceder a las herramientas de zoom.

Estará disponible en la versión 1.3.8

**Comment by i62lotor** [comment]
Cambiadas la teclas para zoom por las siguientes:
Zoom In = pagedown (avanzar página)
Zoom Out = tecla pageup (retroceder página)

**Comment by ghost** [comment]
Enhorabuena, ¡sois unos craks! no hay issue que se os resista.

**Comment by i62lotor** [comment]
Gracias Gonzalo.
Se hace lo que se puede.
