### ISSUE TITLE
Importación de CSV con columnas X/Y

### ISSUE THREAD

**Issue by i62lotor** [geowe/geowe-core#238]
Del issue #228.
Implementar importación desde CSV, para capas de puntos, con las columnas X e Y, en lugar de la columna WKT.
Esta es la opción no recomentada de geoCSV, pero hay usuarios que lo están demandando (@sigdeletras)

**Comment by i62lotor** [comment]
En la próxima versión se podrá importar listados de puntos en forma csv (geoCSV opción puntos).
El formato debe respetar la siguiente forma:
`atributo1;...;atributoN;X;Y`

Por ejemplo (EPSG:25830):
> Name;X;Y
Almería;558353.518288252;4117090.688330406
Cádiz;252874.86049000343;4049205.1603435017
Córdoba;341194.75237248646;4206960.619446362
Granada;476568.0314595196;4129958.374112799
Huelva;162129.8782839346;4166418.759229355
Jaén;461304.74606959824;4208015.46712533
Málaga;346235.625157204;4075817.3504385
Sevilla;262822.45611731976;4146958.7008542903

Para hacer uso de esta funcionalidad basta con seleccionar formato CSV desde el diálogo de importación. El sistema detecta si es en formato WKT o en formato Punto (X/Y).

@sigdeletras la exportación seguirá siendo en formato WKT, ya que es el recomendado.

**Comment by sigdeletras** [comment]
Las primeras pruebas estupendas. Felicidades.

No sé dónde se podría incluir la información especificando el tipo de estructura que debe tener el fichero para cargarse correctamente.
Por ejemplo, en mi archivo las decimales estaba separadas por coma y no cargaba. Quizás se puede indicar en el popup que indica que no se ha cargado el archivo un ejemplo de como de de estar formado.

De todas formas magnifico trabajo.

**Comment by i62lotor** [comment]
Eso lo veo yo como labor de documentación. Si es cierto que el mensaje de error podría ser mas descriptivo. ahora mismo (si no recuerdo mal) es un mensaje genérico para todos los formatos.
Me lo apunto para verlo en futuras versiones.
