### ISSUE TITLE
Poder Geolocalizar por coordenadas en otros sistemas de referencia EJ EPSG: 25830

### ISSUE THREAD

**Issue by aalameda** [geowe/geowe-core#240]
La herramienta de localización por coordenadas ahora permite localizar en WGS84 Según Long y latitud de google, sería perfecto poder utilizar coordenadas X, e Y en metros ETRS89 Huso 30.

Saludos.

**Comment by i62lotor** [comment]
implementado en la versión 1.3.9
![geolocation-dialog-1 3 9](https://cloud.githubusercontent.com/assets/17040784/20625512/133aff08-b314-11e6-8578-5450ee825c88.png)

**Comment by aalameda** [comment]
Genial!!!!


2016-11-25 13:35 GMT+01:00 Rafael López Torres <notifications@github.com>:
