### ISSUE TITLE
Carga desde Github. Selección de proyección y formato

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#251]
En primer, lugar felicidades por la incorporación de la nueva herramienta de cargar información desde GitHub. Esta nueva función incrementará la incorporación de nuevos usuarios con toda seguridad.

En el proceso de carga de las capas, si no se selecciona el código de proyección correcto, la aplicación no indica que no se ha cargado la capa. Pasa lo mismo si no elegimos el tipo de formato.

Una posible solución sería dejar los campos en blanco y que sea obligatorio definirlos. Sin ello no se podría continuar (bloqueo de Aceptar por ejemplo y aviso)

**Comment by jmmluna** [comment]
Hola Patricio,

comentarte que en la versión 1.3.9 está resuelta la validación del formato de los datos en la carga. Con respecto a la proyección se tendrá en cuenta en próximas versiones.

Muchas gracias @sigdeletras 
P.D.: dejo el issue abierto hasta que se aborde la validación de la proyección.

**Comment by i62lotor** [comment]
finalizado en la versión 1.3.12
