### ISSUE TITLE
Nombre de capas con extensión

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#254]
Al cargar una capa desde un repositorio GitHub, no ocurre al cargar por Archivo, el nombre de la capa recoge la extensión del fichero. 
Al descargar dicha capa en local o a Github, GeoWE le añade la la extensión del formato que se haya elegido, por lo que queda repetido o añade la extensión original y la nueva.

Ejemplo:
- Nombre de la capa  por defecto cargada desde github: puntos.geojoson
- Nombre del fichero descargado/almacenado en Github: puntos.geojson.geojson o puntos.geojson.kml....

**Comment by jmmluna** [comment]
En la versión 1.3.8, aunque es cierto que en el nombre de capa se mantiene la extensión, al exportar la capa a GitHub, el nombre es editable. No obstante, es tedioso y se elimina la extensión ya que al guardar en GitHub, GeoWE asigna automáticamente la extensión del fichero en función del formato expecificado. Queda resuelto en la versión 1.3.9. 
Muchas gracias **sigdeletras**!!
