### ISSUE TITLE
Tamaño de la ventana "Análisis geográfico"

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#255]
El tamaño actual de la ventana corta el texto de la parte inferior
![seleccion_347](https://cloud.githubusercontent.com/assets/4746157/20639827/21d24822-b3ce-11e6-9ccd-31490675a37f.png)

**Comment by i62lotor** [comment]
Hola Patricio.
¿Podrías decirme navegador y sistema operativo con el que sucede este problema?
He probado con los siguientes sistemas, y se ve correctamente:
- Linux + Chromium (Version 53.0.2785.143)
- Linux + Firefox (50.0)
- Móvil  Android 5 Firefox y Chrome
- Tablet Android 4.4 Firefox y Chrome

Voy a ampliar el tamaño del diálogo, pero sería interesante detectar donde se está produciendo este tipo de problemas.
Gracias.
Un saludo

**Comment by i62lotor** [comment]
Estará disponble en la versión 1.3.9
Por favor haz las pruebas pertinentes con tu configuración.
Gracias

**Comment by sigdeletras** [comment]
Linux + Firefox (50.0) y por si sirve la resolución (1366 x 768)
