### ISSUE TITLE
Indicadores EPSG para REGCAN95

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#256]
Saludos sería necesario introducir en el listado de Sistemas de coordenadas los correspondientes para las Islas Canarias
Más información [http://blog-idee.blogspot.com.es/2009/06/identificadores-epsg-para-regcan95.html](http://blog-idee.blogspot.com.es/2009/06/identificadores-epsg-para-regcan95.html)

**Comment by i62lotor** [comment]
Hola Patricio. 
GeoWE usa proj4js para realizar las transformaciones entre los diversos sistemas de coordenadas. 
Para añadir (o quitar) nuevos solo hay que tocar el fichero EPSG.js. De esta manera se podría personalizar en cada despliegue concreto.

Atendiendo a tu petición voy a incluir los que faltaban, y las islas afortunadas quedarán cubiertas de en la demo de la siguiente manera:

- EPSG:32627: [WGS 84 / UTM zone 27N](http://spatialreference.org/ref/epsg/32627/)
- EPSG:32628: [WGS 84 / UTM zone 28N](http://spatialreference.org/ref/epsg/32628/)
- EPSG:4082: [REGCAN95 / UTM zone 27N](https://epsg.io/4082)
- EPSG:4083: [REGCAN95 / UTM zone 28N](https://epsg.io/4083)

Estará disponible en la versión 1.3.9

**Comment by sigdeletras** [comment]
Estupendo. Así quedan recogidos todos los SRC nacionales.
