### ISSUE TITLE
Actualizar versión de fichero al modificar ficheros en GitHub

### ISSUE THREAD

**Issue by jmmluna** [geowe/geowe-core#263]
En la versión 1.3.9, cuando se modifica el contenido de un fichero en GitHub, se crea un nuevo SHA en GitHub, es decir, una nueva versión del fichero que es distinta a la que mantiene GeoWE en la sesión de trabajo. En esta versión de GeoWE, para seguir trabajando sobre esa capa ya modificada requiere que sea cargada para actualizar la versión del fichero correspondiente de  GitHub.
En próximas versiones se requiere agilizar este versionado del fichero de manera automática y evitar así tener que estar recargando los últimos cambios efectuados en el fichero

**Comment by i62lotor** [comment]
Si al modificar el fichero de GitHub se produce un error (probablemente por que el fichero existente en GitHub es diferente), sería interesante indicar al usuario de esta situación y facilitarle el enlace para cargarlo, o indicarle como.
Por ejemplo:
El fichero que intenta modificar ya ha sido cambiado por otro usuario. ¿Desea cargarlo en su sesión actual de geowe?

**Comment by rcejudo8** [comment]
Me parece muy bueno esta modificación. Un saludo

**Comment by rcejudo8** [comment]
Ayer pude comprobar con la versión 1.3.10 que ya puedes modificar el fichero de la sesión de trabajo sin tener que crear nuevo fichero. Un saludo

**Comment by i62lotor** [comment]
A partir de la versión 1.3.11 cuando se modifica  una capa en GitHub se actualiza la carga de geowe, de manera que se puede seguir editando y modificando en github sin necesidad de volver a cargar la capa.
