### ISSUE TITLE
Carga de raster wms

### ISSUE THREAD

**Issue by rcejudo8** [geowe/geowe-core#269]
No consigo que me funcione los wms en geowe. 
URL:http://xxxxxxx/geoserver/LOTE3/wms?service=WMS&version=1.1.0&request=GetMap&layers=LOTE3:sin_acceso_lote3&styles=&bbox=433289.90625,4469974.5,442027.65625,4488292.0&width=366&height=768&srs=EPSG:25830&format=image%2Fjpeg

image/jpeg

El resultado en geowe  es un mosaico del wms en 8 0 10 imagenes continuas.

Me gustaría saber si estamos haciendo algo mal o falta por depurar los wms.

Un saludo

**Comment by i62lotor** [comment]
Hola Rubén

La URL que pones es la que escribes en el campo url?

Aquí tienes un ejemplo de cómo cargar capas WMS (aunque en una versión anterior de GeoWE es muy similar)
http://geowegis.blogspot.com.es/2015/12/cargando-ortos-sigpac.html

Y en el siguiente enlace tienes más ejemplos (a partir del punto 7)
http://geowegis.blogspot.com.es/2016/11/caracterizacion-del-territorio.html

Si te parece bien dime los datos del servidor desde el que necesitas cargar la capa y lo intento yo.

Un saludo

**Comment by rcejudo8** [comment]
Hola gracias por la contestación a pesar del ejemplo, no me funciona la capa wms.
URL: http://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_mapa_pendientes_10?
Capa : pendiente_10
Imagen: image/png

Te adjunto un ejemplo de la Url que no consigo que cargue en geowe(sale pero en mosaico:
URL:http://www.valorizaservicios.com/geoserver/LOTE3/wms?service=WMS&version=1.1.0&request=GetMap&layers=LOTE3:sin_acceso_lote3&styles=&bbox=433289.90625,4469974.5,442027.65625,4488292.0&width=366&height=768&srs=EPSG:25830&format=image%2Fpng
Capa:sin_acceso_lote3
image/png


Muchas gracias

**Comment by geowe** [comment]
Rubén he cargado la capa.
En el campo url debes poner esto:
http://www.valorizaservicios.com/geoserver/LOTE3/wms?

Se muestra una capa con imágenes de polígonos, por ejemplo: centro de formación ocupacional los Cármenes o el colegio público Hernán Cortés.

No puedo hacerte una captura de pantalla desde la tablet. En cuanto pueda con el pc lo vuelvo a cargar. Pero eso ya otro día

Buenas noches.

**Comment by rcejudo8** [comment]
Gracias, de esta manera ya funciona perfectamente y lo que más no sorprende es que se obtiene la información del wms de una manera rápida, aunque sea una capa de más de 100000 elementos. Un saludo

**Comment by i62lotor** [comment]
¡Estupendo! cerramos entonces este issue. Si tienes alguna duda/problema mas coméntalo añadiendo mas issues.

Un saludo
