### ISSUE TITLE
Falla el guardado de datos en GitHub

### ISSUE THREAD

**Issue by aalameda** [geowe/geowe-core#270]
Buenas, 
He intentado guardar una capa en Github, y cuando pulsas guardar, no hace nada.
no se si es problema mío o de la nueva versión.

Saludos.

**Comment by i62lotor** [comment]
Confirmado el error. 
He intentado guardar una capa de puntos (centroides de las provincias de Andalucía) y se produce un error.
La capa solo tiene un atributo provincia, que es el nombre de las proviancias.

**Comment by rcejudo8** [comment]
A nosotros también nos está fallando el guardado de capas. Para ir guardando tenemos que ir generando capas y capas.

**Comment by i62lotor** [comment]
La solución está implementada en el fork i62lotor/geowe-core (versión 1.3.11).
En cuanto pueda realizar mas pruebas haré el pull-request para integrarlo en el repo oficial y que esté disponible para el despliegue de la siguiente versión.

**Comment by i62lotor** [comment]
Solucionado en la versión 1.3.11
Probado tanto para crear como para modificar.
