### ISSUE TITLE
Estilos: Etiqueta de atributo

### ISSUE THREAD

**Issue by i62lotor** [geowe/geowe-core#273]
Se pierde el estilo de etiquetado de atributo al cambiar de capa en el administrador de capas.
También pierde el estilo de relleno.

**Comment by i62lotor** [comment]
El error está en el onchange layer event de los estilos, que actualiza si tiene Style, pero no si tiene styleMap.
@atamunoz te toca arreglar esto :op

**Comment by atamunoz** [comment]
OK, voy a echarle un vistazo!!

**Comment by atamunoz** [comment]
Solventado en versión 1.4.3
