### ISSUE TITLE
Codificación de atributos

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#277]
En algún momento de la creación o carga de capas debería poder indicarse el sistema de codificación de los datos alfanuméricos. Al carga una capa y activar la opción Filtrar, parecen los típicos símbolos que indican que no se está utilizando el sistema correcto.
![seleccion_499](https://cloud.githubusercontent.com/assets/4746157/22365328/1db8c3a4-e477-11e6-92f8-8d7fc02a38a2.png)

**Comment by i62lotor** [comment]
Lo mas probable es que los datos en origen no estén en UTF-8.

**Comment by i62lotor** [comment]
Había un problema a la hora de guardar en GitHub, la información de la capa no se codificaba correctamente a UTF-8.

Queda solucionada en la versión 1.4.6
