### ISSUE TITLE
Soporte de estilos a nivel de feature

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#280]
Sería interesante el poder aplicar estilos a nivel de feature independientemente de los estilos de la capa.

**Comment by atamunoz** [comment]
Esta nueva funcionalidad ha sido implementada en la versión 1.4.8. Ahora cuando abres el diálogo de estilos y existen elementos seleccionados en la capa, los cambios realiados en dicho diálogo se aplicarán únicamente a los elementos seleccionados.

NOTA: El estilo de vértice solamente se aplica a capas de puntos. Para líneas y polígonos, siempre prevalece el estilo de general de la capa.
