### ISSUE TITLE
Estilos de atributo se queda barra de progreso

### ISSUE THREAD

**Issue by i62lotor** [geowe/geowe-core#289]
Al habilitar los estilos de atributo, y pulsar aplicar (sin seleccionar atributo del combo), se queda la barra de progreso.
Debería ser obligatorio seleccionar aldo del combo de atributo.
Igual pasa con el tamaño de fuente.

**Comment by i62lotor** [comment]
Pasa igual en los estílos temáticos

**Comment by atamunoz** [comment]
Solventado en versión 1.4.4
