### ISSUE TITLE
Estilos: habiliatar label cambia el relleno

### ISSUE THREAD

**Issue by i62lotor** [geowe/geowe-core#297]
Al habilitar el estilo de atributos y pulsar aplicar, sin seleccionar atributo ni tamaño salta una ventana de error (podría ser aviso), y cambia el color de relleno de los elementos de la capa.

**Comment by i62lotor** [comment]
He probado tanto con capas del catálogo, como con capas de fichero.

1. Cargar capa de Andalucía del catálogo
2. Abrir panel de estilos
3. Ir a la pestaña "label attribute"
4. Pulsar aplicar

Resultado: Ventana de error indicando que no se ha especificado atributo ni tamañao de fuente (por cierto el tamañao de fuente se podía poner uno por defecto). Se cierra el panel de estilos. Se cambia el fillColor de toda la capa.

**Comment by i62lotor** [comment]
Si tienes elementos seleccinados e intentas aplicar estilo de atributo, como anteriormente salen tantos diálogos de error como elementos tengas seleccionados. Imagina que tengo 15 elementos, uf!!

**Comment by i62lotor** [comment]
Después de aplicar estilos por elemento, parece que se quedan seleccionadas, eso indica el diálogo, pero en el mapa aparecen con el estilo aplicado, no con el de selección (verde). Hay que pulsar varias veces sobre el elemento para que funcione la selección.
Parece que los elementos se quedan seleccionados después de aplicar los estilos.

**Comment by i62lotor** [comment]
Cuando se cargan capas del catálogo o desde fichero, al abrir el diálogo de estilos no reconoce bien los estilos de la capa.

**Comment by i62lotor** [comment]
Color Temático.
Si no poner el atributo se cierra el panel de estilos y salta un mensaje de error indicando que no se ha seleccionado ningún atributo. ¿No debería quedarse el panel abierto?

**Comment by atamunoz** [comment]
Muy buen beta-testing compañero! Todos los errores han sido solucionados en la versión 1.4.8.

Saludos!
