### ISSUE TITLE
Leyenda de mapa

### ISSUE THREAD

**Issue by i62lotor** [geowe/geowe-core#304]
Al habilitar los estilos a nivel de elemento, cuando se crean las leyendas (tanto temática como de las capas) ya no representan correctamente la visualización actual del mapa.

**Comment by atamunoz** [comment]
Se ha modificado el comportamiento para que al aplicar el estilo de color temático, se eliminen los estilos a nivel de feature. De esta manera la leyenda siempre representará correctamente la visualización del mapa. Por supuesto, se avisará al usuario cuando active el color temático.
