### ISSUE TITLE
Pruebas con GeoJSON CSS

### ISSUE THREAD

**Issue by ghost** [geowe/geowe-core#308]
Hola a todos,

Haciendo algunas pruebas de generación de GeoJSON, he advertido algún problema que paso a detallaros.

Os cuento los pasos que he seguido para que los podáis reproducir y analizar la cuestión:

0.- Arranco con un proyecto nuevo

1.- Añado el GeoJSON https://raw.githubusercontent.com/datourbano/madrid/master/movilidad/bici/vialidad/28079_calles_tranquilas.geojson

2.- Aplico color temático en base al atributo TX_CAPA, lo que genera una leyenda de dos clases:
Color Marrón: CICLOCALLES
COlor morado: PEATONAL

3.- Exporto todo el fichero como GeoJSON_CSS

Parece que el fichero resultante no guarda la especificación correctamente. La etiqueta "style" tiene el siguiente contenido:
"style":{"fill":true, "fillColor":"${getColor}", "fillOpacity":0.5, "weight":3, "color":"${getColor}", "opacity":1}

Si trabajo con un nuevo proyecto de GeoWE, no soy capaz de cargar el fichero GeoJSON_CSS que he generado anteriormente.

Esto ocurre también cuando simbolizo a nivel de feature.

Como siempre. Gracias y enhorabuena.

GonZaLo

**Comment by jmmluna** [comment]
Hola @gonzalolopezgarcia 

muchas gracias por dedicar tiempo a realizar pruebas con el formato GeoJSON CSS. A partir del GeoJSON que nos has especificado, he estado haciendo pruebas. Comentarte que por ahora solo se soportan los **estilos básicos** (a nivel de capa): color de relleno, color de línea, ancho de línea y opacidad.

En esta última versión 1.4.8, se ha mejorado la herramienta de estilos para poder aplicar estilos personalizados a nivel de feature (que no se soportaba en versiones aneriores), y en las próximas versiones esperamos integrar los estilos básicos a nivel de feature en el formato GeoJSON CSS.

Se intentará que vaya evolucionando el formato GeoJSON CSS en cada nueva versión. Vamos poco a poco, adaptando la plataforma y esperamos que la prueba que has intentado hacer funcione correctamente lo antes posible.
 
Seguimos en contacto!!
Un saludo!!
[calles_tranquilas.txt](https://github.com/geowe/geowe-core/files/769235/calles_tranquilas.txt)

![geowe 1 4 8 beta](https://cloud.githubusercontent.com/assets/17873390/22861542/b4c60a6c-f11b-11e6-9417-9db1b82e6064.png)

**Comment by jmmluna** [comment]
Hola @gonzalolopezgarcia

el formato GeoJSON CSS en GeoWE sigue evolucionando. Desde la plataforma ya se contempla cargar y exportar capas en GeoJSON CSS con estilos tanto a nivel de capa como a nivel de feature. En cuanto a los estilos, aparte de los estilos básicos ya contemplados, ahora ya también se incopora soporte para iconos. 

He estado haciendo pruebas con datos de la La Rioja: "Acotados y vedados de setas y trufas.geojson", "Albergues.geojson" y "EDAR.geojson". Todo correcto!!

![geowe-geojsoncss-rioja](https://cloud.githubusercontent.com/assets/17873390/23017202/a9e1608a-f439-11e6-8d5b-a4e2b4e9d42c.png)

Comentarte que para el caso de capas en las que todos los elementos compartan un mismo estilo, ya no es necesario definir el estilo por elemento, en su lugar se define una sola vez con estilo a nivel de capa. Te adjunto la capa original de "EDAR.geojson" (55 KB) y la generada desde GeoWE "EDAR.geojson_css" (44 KB).

[EDAR.geojson.txt](https://github.com/geowe/geowe-core/files/779763/EDAR.geojson.txt)
[EDAR.geojson_css.txt](https://github.com/geowe/geowe-core/files/779765/EDAR.geojson_css.txt)

Te adjunto también capturas de las pruebas realizadas con estilos desde GeoWE y su interoperabilidad con Leaflet.

![geowe-geojsoncss-basic-style](https://cloud.githubusercontent.com/assets/17873390/23018073/f6c8ae6e-f43c-11e6-954c-efd14246fb31.png)
![geowe-leaflet-geojsoncss](https://cloud.githubusercontent.com/assets/17873390/23018075/fa6a520c-f43c-11e6-8138-2bf7c5ba6c53.png)

He intentado colaborar con Alexander Burtsev para completar el plugin 
https://github.com/albburtsev/Leaflet.geojsonCSS/pull/1, pero no he recibido respuesta. He decidido elaborar un nuevo plugin más completo del formato GeoJSON CSS para verificar toda la funcionalidad y de paso esté disponible públicamente. Cuando estén todos los estilos soportados y verificados con el nuevo plugin te avisaré y estará disponible en mi cuenta de GitHub. No obstante si lo necesitas antes para comprobar capas te lo facilito.

Aún queda por incorporar los estilos temáticos para que funcione correctamente la prueba que hiciste. Ya falta menos!!.

Un saludo!!

**Comment by jmmluna** [comment]
En la versión 1.4.14 el formato GeoJSON CSS soporta:

- Estilos a nivel de capa, de feature y ambos.
- Estilos básicos (color relleno, opacidad relleno, color línea, grosor línea).
- Estilo de Iconos.
- Color temático.

@gonzalolopezgarcia, la prueba de **calles_tranquilas.geojson** aplicando color temático por el atributo TX_CAPA ya te funcionará a partir de la versión 1.4.14.

Ya nos cuentas que tal las pruebas y si observas que falta algo.

Un saludo!!
