### ISSUE TITLE
Cargar capas WFS

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#31]
Soporte para carga de capas vectoriales WFS

**Comment by i62lotor** [comment]
La carga de datos usando WFS, está implementada, pero la funcionalidad no es del todo completa.
Se ha detectado que la funcionalidad no es compatibles con algunos servicios WFS. Esta todavía por confirmar si es por GeoWE o por el no cumplimiento del estandar de algunos servicios.
Por otro lado, cuando se cargan elementos por WFS solo está cargando la información geométrica, no mostrando los atributos alfanuméricos de los elementos de la capa.

**Comment by i62lotor** [comment]
Se re-implementa la funcionalidad. 
Queda resuelto este issue en la versión 1.3.4
En esa versión se podrán cargar elementos desde un servicio WFS por BBox o haciendo una consulta CQL
