### ISSUE TITLE
Transparencia en icono

### ISSUE THREAD

**Issue by sigdeletras** [geowe/geowe-core#311]
Al utilizar el estilo avanzado, usando una imagen externa la representa por defecto con transparencia y no se puede modificar.

![image](https://cloud.githubusercontent.com/assets/4746157/22864924/68edb498-f15a-11e6-9a42-54b4ecd48d24.png)

**Comment by i62lotor** [comment]
La transparencia está a nivel de capa. Se puede cambiar en la primera pestaña (Línea y Color), en la opacidad del relleno.

**Comment by atamunoz** [comment]
Efectivamente, la transparecia se puede configurar en la primera pestaña del diálogo de estilos.

**Comment by sigdeletras** [comment]
Lo miraré. Gracias
