### ISSUE TITLE
Unión de elementos geográficos con tablas alfanuméricas por campo clave.

### ISSUE THREAD

**Issue by aalameda** [geowe/geowe-core#313]
La propuesta se divide en dos:

1. Se propone que de igual manera que GeoWE carga información gráfica, pueda cargar información alfanumérica.
2. Se propone de dicha información (alfanumérica) pueda ser asignada a elementos geográficos mediante  por un campo clave.

Ejemplo: Tenemos la capa de municipios con un campo "id_municipio", queremos asignarle valores estadísticos provenientes de datos; CSV, Json, etc ,  los que también hay un campo "id_municipio".

La propuesta es que a los atributos de la capa "municipios" se les pudieran añadir los datos de datos estadísticos, para generar datos Geoestadisticos. mediante un _"join"_ de tablas por el campo  "id_municipio"

Para casos genéricos GeoWE preguntaría cuales son los campos de unión de las diferentes tablas.

**Comment by i62lotor** [comment]
Implementado en la versión 1.4.12
Podra vinculuar información alfanumérica desde un fichero o desde una url.
La herramienta está el en diálogo de información de capa.
El fichero con los datos a vincular deberá cumplir lo siguiente:
- Estar en formato CSV, separado por ; (punto y coma)
- La primera línea debe indicar el nombre de los atributos
- Las demás líneas indicarán los valores.
- Si alguna línea de valores está mal formada se ignorará
- Debe existir al menos un atributo por el que vincular los datos a la capa, es decir, que exista como atributo en la capa.

Ejemplo de csv para vincular a la capa de Andalucía existente en la demo:

> name;poblacion;empresas;pib
> 1;1000;10;no lo sé
> 2;2000;20;888383
> 3;3000;30;ññña
> 10;10;10;10
> 5;5000;50;quinientos mil

**Comment by aalameda** [comment]
Genial!!!, estupendo para enriquecer los dato con contenido temático.

Deseando probarlo,

Muchas gracias.
