### ISSUE TITLE
Carga de múltiples capas al vuelo

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#32]
Sería interesante poder cargar al vuelo múltiples capas, bien por url o por fichero.

**Comment by geowe** [comment]
Por ahora no se va a implementar

**Comment by geowe** [comment]
@jmmluna esto quedaría resuelto con el formato de proyecto.
Clasifico el issue como mejora, y lo puedes cerrar cuando estimes oportuno.

**Comment by jmmluna** [comment]
Desde la versión 1.4.0 ya se soporta el formato GeoWE Project que cargará múltiples capas al vuelo
