### ISSUE TITLE
Estilos temáticos con features seleccionadas.

### ISSUE THREAD

**Issue by i62lotor** [geowe/geowe-core#325]
Caso de prueba:
1. cargo capa
2. aplico color temático
3. selecciono un feature
4. abro diálogo de estilos y se abre en la pestaña de color tematico, cuando el color tematico no se admite para estilos de features

**Comment by atamunoz** [comment]
Solucionado. Estará disponible en la siguiente versión.

**Comment by atamunoz** [comment]
Ahora cuando se da esta circunstancia, se selecciona automáticamente la primera pestaña del diálogo de estilos.
