### ISSUE TITLE
Poder elegir campo y separador, de las tablas en "vincular datos desde CSV"

### ISSUE THREAD

**Issue by aalameda** [geowe/geowe-core#327]
Actualmente se pueden vincular datos alfanuméricos a gráficos mediante el vinculador,

la versatilidad de la herramienta aumentaría muchos enteros, si se pudiera elegir:

1. El separador, ejemplos: "," , ";", " ", "|" ,Tab u otros
2. El campo de unión de la tablas "capa gráfica" y "tabla a vincular"

Se proponen estas mejoras, ya que GeoWE puede ser una herramienta perfecta para generar geodatos temáticos on line, a partir de datos en la nube.

**Comment by i62lotor** [comment]
Listo para probar a partir de la versión 1.4.17

**Comment by aalameda** [comment]
Genial!! muchas gracias;)
