### ISSUE TITLE
Extensión geojson_css

### ISSUE THREAD

**Issue by ghost** [geowe/geowe-core#346]
Hola a todos.

Antes de que se popularice el formato GeoJSON CSS gracias a GeoWE, creo que es interesante hacer una reflexión respecto a la extensión que utilizáis para guardar este formato.

He visto que este tipo de ficheros los almacenáis con la extensión ".geojson_css".

Siendo como son ficheros GeoJSON, mi opinión personal se inclina por conservar la extensión ".geojson". De esta manera los programas que entienden este formato lo reconocerían, en tanto que no reconocen el formato geojson_css.

El ejemplo más claro es el propio github, ya  que mientras es capaz mostrar en forma de mapa un archivo con extensión ".geojson", no entiende como fichero geográfico los archivos con extensión "geojson_css".

La solución que sugiero es utilizar una extensión del modo".css.geojson"

Un saludo.

GonZaLo

**Comment by jmmluna** [comment]
Hola @gonzalolopezgarcia 

buena propuesta,  lo adaptaremos para la próxima versión.

Un saludo

**Comment by geowe** [comment]
Implementado en la versión 1.5.4.
La nueva extensión será: css-geojson

**Comment by ghost** [comment]
Esto creo que no solucionaría la cuestión que se planteaba. ya que lo que se precisa es que la extensión sea ".geojson" para que el resto de aplicaciones lo puedan reconocer como tal. Por este motivo se proponía la extensión compuesta "css.geojson" y no "css-geojson".

**Comment by i62lotor** [comment]
cambiado a css.geojson. Disculpa el lapsus.
Un saludo
