### ISSUE TITLE
Cargar wms

### ISSUE THREAD

**Issue by georizzo** [geowe/geowe-core#353]
Hola! Necesito hacerles una consulta. 
No consigo que me funcione los wms en geowe.

http://atmgis.mendoza.gov.ar/geoserver/cartografia/wms?

http://idemza2.mendoza.gov.ar/geoserver/IDEMendoza/wms?

Me gustaría saber cómo ingresar los datos correctamente porque no logro visualizar los datos. Me pueden ayudar?
Un saludo

**Comment by i62lotor** [comment]
Hola @georizzo.
Para cargar capas WMS del servicio  atmgis.mendoza.gov.ar puedes usar los siguientes valores:
**Url:** 
`http://atmgis.mendoza.gov.ar/geoserver/cartografia/wms`

**formato:** 
`image/png`

**Nombre de la capa:**
Algunas capas definidas en el servicio (ver capabilities):
```
ALVEAR_VUT_RURAL
ALVEAR_VUT_URBANO
BARRIOS_PROVINCIA
DBGIS.DBO.PARCELAS_SUBURBANAS_GUAYMALLEN
```
Para obtener las capabilities (supongo que ya lo sabes)
[http://atmgis.mendoza.gov.ar/geoserver/cartografia/wms?request=getCapabilities](http://atmgis.mendoza.gov.ar/geoserver/cartografia/wms?request=getCapabilities)

He notado que la carga/refresco(al cambiar de zoom por ejemplo) me va  un poco lento, no se si es por mi conexión a internet o por el servicio. Puede que al añadir una capa tarde unos segundos en aparecer.

Te adjunto una captura de pantalla con algunas capas y el  WMS info de algún elemento.
![atmgis-mendoza](https://user-images.githubusercontent.com/17040784/59561764-34c41980-9024-11e9-8124-37bac59dc748.png)

**Comment by i62lotor** [comment]
Al igual que para el servicio anterior, para cargar capas WMS de idemza2.mendoza.gov.ar puedes rellenas la información de la siguiente manera:

**Url:**
`http://idemza2.mendoza.gov.ar/geoserver/IDEMendoza/wms`

**Formato:**
`image/png`

**Nombre de la capa:**
Algunas capas definidas en el servicio (ver capabilities):
```
aysam_agua
danielbritos_areas_petroleras_2015_4326_bis
danielbritos_rutas_mendoza_dpv
```
Adjunto captura de pantalla con capas cargadas de este servicio.

Espero que esta información te sea de utilidad.

Gracias por usar GeoWE (recuerda que la aplicación desplegada en map.geowe.org es una versión de demostración)
Ya nos cuentas que tal.

![idemza-mendoza](https://user-images.githubusercontent.com/17040784/59561909-ea439c80-9025-11e9-8ea3-5a49b7369306.png)

**Comment by georizzo** [comment]
Excelente!!! Ahí logré subir las capas, muchísimas gracias!
Abrazo

**Comment by i62lotor** [comment]
¡Estupendo! cierro entonces este issue.
