### ISSUE TITLE
Al eliminar elementos el díalogo de información de la capa no lo refleja

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#52]
Cuando se eliminan elementos de una capa al abrir el diálogo de información de la capa sigue mostrando los que había antes de borrar

**Comment by geowe** [comment]
No lo refleja al eliminar de uno en uno. Al elminiar los seleccionados si lo hace bien.

**Comment by jmmluna** [comment]
Resuelta en la versión 0.1.84-Alpha tanto en la herramienta de borrado del panel principal como en la herramienta de borrar elementos desde la ventana de información de la capa
