### ISSUE TITLE
Herramienta División 

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#56]
Al dividir elementos tipo línea, sale un información indicando que no hay ningún polígono, y se queda la barra de progreso moral, obligando a recargar la aplicacion

**Comment by jmmluna** [comment]
Resuelto en la version  0.1.78-Alpha. Esta herramienta solo divide polígonos en otro caso se para el proceso de ejecución, se informa al usuario y se limpia la línea de corte temporal.
