### ISSUE TITLE
Herramienta envelope

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#57]
Al calcular envelope a una capa compuesta por polígonos, puntos y lineas se produce el siguiente error:
Error This method does not support GeometryCollection arguments

En tabletas Android con chrome

**Comment by jmmluna** [comment]
Resuelto en la versión 0.1.78-Alpha. Se mejora la funcionalidad de tal manera que cuando la capa se compone de diferentes tipos de geometrías se agrupan los Envelopes resultantes en función del tipo.
