### ISSUE TITLE
Operacion espacial Diferencia

### ISSUE THREAD

**Issue by i62lotor** [geowe/geowe-core#58]
La operación diferenica no oculta el diálogo de progreso.
Caso de prueba:
1. Cargo la capa lebrija del catálogo
2. Duplico la capa
3. Aplico diferencia entre ambas capas

(igual sucede si las capas son las de lebrija y Andalucía)

**Comment by jmmluna** [comment]
Resuelto en la versión 0.1.77-Alpha
