### ISSUE TITLE
Aplicación no responde al cambiar de capa despues de hacer zoom a elementos selecionados

### ISSUE THREAD

**Issue by jmmluna** [geowe/geowe-core#73]
La aplicación no responde cuando se hace zoom a la selección de los elementos seleccionados de una capa y posteriormente se cambia de capa desde el panel de estado.

**Comment by i62lotor** [comment]
Se queda bloqueda después de hacer zoom a los elementos seleccionados e intentar cualquier otra herramienta.

**Comment by i62lotor** [comment]
Solucionado en la versión 0.1.91
