### ISSUE TITLE
Exportar capa con muchos elementos

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#8]
Al Exportar una capa con muchos elementos, el navegador va muy lento, y en ocasiones se queda colgado, indicando que el script tarda mucho en responder.
He probado a exportar a GML la capa de la demo de Lebrija.

**Comment by i62lotor** [comment]
Se realiza la tarea en un hilo. Se debe probar con capas pesadas.

**Comment by i62lotor** [comment]
Se ha mejorado el rendimiento.
