### ISSUE TITLE
operación espacial Intersección

### ISSUE THREAD

**Issue by i62lotor** [geowe/geowe-core#82]
La operación espacial entre capas de Intersección produce resultados inesperados.

He probado con la pada de Andalucía y la he duplicado.

En la consola sale el siguiente mensaje:
SyntaxError.json.parse: unexpected character...

y muestra esto en la respuesta:

//OK[14,2,13,2,12,2,11,2,10,2,9,2,8,2,7,2,6,2,5,2,4,2,3,2,12,1,["java.util.ArrayList/4159755760","java.lang.String/2004016611","POLYGON ((-704628.4637855522 4425454.309676379, -698498.6470812191 4427016.737613595, -695975.560965772 
....
1037 4593584.036008176, -626903.7918234421 4599170.163658212, -621607.1021808953 4598285.531839798))"],0,7]

**Comment by jmmluna** [comment]
Resuelto en la versión 0.2.35
