### ISSUE TITLE
Operación espacial Buffer a capa

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#87]
Al aplicar un Buffer de 1 a la capa completa de lebrija, tarda mucho tiempo, y al final da un error:

"error 0".

**Comment by jmmluna** [comment]
Este error es provocado porque la capa de Lebrija presenta errores geométricos. Al aplicar análisis espacial realizando geoprocesos sobre las capas, éstas deberían de estar validadas geométricamente para evitar respuesta inesperados o resultados incorrectos topológicamente hablando. Para dar solución a este issue, se va a facilitar una herramienta de validación geométrica que estará disponible para la siguiente versión del día 10 de Junio.
