### ISSUE TITLE
Cambiar nombre de la capa

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#89]
Posibilidad de cambiar el nombre de una capa después de crearla.
La opción mas cómoda sería desde el diálogo de información de la capa.

**Comment by i62lotor** [comment]
Se incluye la funcionalidad, para cambiar el nombre de las capas vectoriales. Por ahora las capas Raster se quedan con el nombre de carga.
Se puede renombrar la capa vectorial desde el diálogo de información de capa.
