### ISSUE TITLE
Opción de crear atributos de la capa al crear capa nueva

### ISSUE THREAD

**Issue by geowe** [geowe/geowe-core#97]
Al crear una capa vacía, dar la posibilidad de crear sus atributos alfanuméricos (esquema). Para tener esa opción mas accesible al usuario.

**Comment by i62lotor** [comment]
A partir de la versión 0.2.36, al crear una capa vacía, hay un check, que da la posibilidad al usuario de acceder a la creación de los atributos de la capa.
